/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import java.awt.CardLayout;
import java.awt.event.ActionEvent;
import java.beans.PropertyChangeListener;
import java.beans.PropertyChangeSupport;
import javax.swing.JOptionPane;
import model.Commune;
import model.CommuneListModel;

/**
 *
 * @author m.arakelian
 */
public class CommuneView extends javax.swing.JPanel {

    private PropertyChangeSupport listeners = new PropertyChangeSupport(this);
    private CommuneEditPanel communeEditPanel = new CommuneEditPanel();

    @Override
    public void addPropertyChangeListener(PropertyChangeListener l) {
        listeners.addPropertyChangeListener(l);
    }

    public void setCommuneListModel(CommuneListModel communeListModel) {
        this.jListCommune.setModel(communeListModel);
    }

    public CommuneView() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jListCommune = new javax.swing.JList<>();
        jButtonSuppr = new javax.swing.JButton();
        jButtonVoirUtilisateur = new javax.swing.JButton();
        jButtonModif = new javax.swing.JButton();
        jButtonAjout = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        jListCommune.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(jListCommune);

        jButtonSuppr.setText("Supprimer");
        jButtonSuppr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSupprActionPerformed(evt);
            }
        });

        jButtonVoirUtilisateur.setText("voir les utilisateurs");
        jButtonVoirUtilisateur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVoirUtilisateurActionPerformed(evt);
            }
        });

        jButtonModif.setText("modifier");
        jButtonModif.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModifActionPerformed(evt);
            }
        });

        jButtonAjout.setText("Ajouter");
        jButtonAjout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAjoutActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI Historic", 1, 36)); // NOI18N
        jLabel5.setText("Liste des communes");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 581, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jButtonAjout, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonModif, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonSuppr, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonVoirUtilisateur, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(117, 117, 117)
                        .addComponent(jLabel5)))
                .addContainerGap(75, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonSuppr, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonModif, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonAjout, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonVoirUtilisateur, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(46, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSupprActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSupprActionPerformed

        int result = JOptionPane.showConfirmDialog(this, "Etes vous certain de supprimer cette commune ?");
        if (result == JOptionPane.OK_OPTION) {
            Commune selected = getSelectedCommune();
            if (selected != null) {
                listeners.firePropertyChange("deleteSelectedCommune", null, selected);
            } else {
                JOptionPane.showMessageDialog(this, "Veuillez sélectionner une commune avant de supprimer.");
            }
        }
    }//GEN-LAST:event_jButtonSupprActionPerformed

    private void jButtonVoirUtilisateurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVoirUtilisateurActionPerformed

        Commune selected = getSelectedCommune();
        if (selected != null) {
            listeners.firePropertyChange("showUsersForCommune", null, selected);
        } else {
            JOptionPane.showMessageDialog(this, "Veuillez sélectionner une commune avant de voir ses utilisateurs.");
        }


    }//GEN-LAST:event_jButtonVoirUtilisateurActionPerformed

    private void jButtonModifActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModifActionPerformed
        this.communeEditPanel.setJLabelModifCommune("Modification");
        Commune selected = getSelectedCommune();
        if (selected != null) {
            communeEditPanel.setNom(selected.getNom());
            communeEditPanel.setCodePostal(selected.getCodePostal());
            communeEditPanel.setDescription(selected.getDescription());

            String[] options = {"Valider", "Annuler"};
            int result = JOptionPane.showOptionDialog(
                    this,
                    communeEditPanel,
                    "Modifier la commune",
                    JOptionPane.OK_CANCEL_OPTION,
                    JOptionPane.PLAIN_MESSAGE,
                    null,
                    options,
                    options[0]
            );
            if (result == JOptionPane.OK_OPTION) {
                listeners.firePropertyChange("validModifCommune", null, selected);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Veuillez sélectionner une commune avant de modifier.");
        }
    }//GEN-LAST:event_jButtonModifActionPerformed

    private void jButtonAjoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAjoutActionPerformed
        this.communeEditPanel.setJLabelModifCommune("Ajout");
        this.communeEditPanel.setNom("");
        this.communeEditPanel.setDescription("");
        this.communeEditPanel.setCodePostal(0);
        String[] options = {"Valider", "Annuler"};
        int result = JOptionPane.showOptionDialog(
                this,
                this.communeEditPanel,
                "Ajout nouvelle commune",
                JOptionPane.OK_CANCEL_OPTION,
                JOptionPane.PLAIN_MESSAGE,
                null,
                options,
                options[0]
        );
        if (result == JOptionPane.OK_OPTION) {
            listeners.firePropertyChange("validNouvelleCommune", null, null);
        }
    }//GEN-LAST:event_jButtonAjoutActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAjout;
    private javax.swing.JButton jButtonModif;
    private javax.swing.JButton jButtonSuppr;
    private javax.swing.JButton jButtonVoirUtilisateur;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JList<String> jListCommune;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables

    public String getNom() {
        return this.communeEditPanel.getNom();
    }

    public int getCodePostal() {
        return this.communeEditPanel.getCodePostal();
    }

    public String getDescription() {
        return this.communeEditPanel.getDescription();
    }

    public Commune getSelectedCommune() {
        Object value = this.jListCommune.getSelectedValue();
        if (value instanceof Commune) {
            return (Commune) value;
        }
        return null;
    }

    public Integer getSelectedCommuneId() {
        return this.jListCommune.getSelectedIndex();
    }

    public void useLayout(String cardtext) {
        CardLayout card = (CardLayout) this.getLayout();
        card.show(this, cardtext);
    }
}
