/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

/**
 *
 * @author m.arakelian
 */
public class CommuneEditPanel extends javax.swing.JPanel {

    /**
     * Creates new form CommuneEditPanel
     */
    public CommuneEditPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextFieldEditDescrip = new javax.swing.JTextField();
        jTextFieldEditCodePostal = new javax.swing.JTextField();
        jTextFieldEditNom = new javax.swing.JTextField();
        jLabelModifCommune = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        jTextFieldEditDescrip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldEditDescripActionPerformed(evt);
            }
        });

        jTextFieldEditCodePostal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldEditCodePostalActionPerformed(evt);
            }
        });

        jTextFieldEditNom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldEditNomActionPerformed(evt);
            }
        });

        jLabelModifCommune.setFont(new java.awt.Font("Segoe UI", 0, 28)); // NOI18N
        jLabelModifCommune.setText("Ajout commune");

        jLabel2.setText("Nom :");

        jLabel3.setText("Code Postal :");

        jLabel4.setText("Description :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldEditDescrip, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldEditCodePostal, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldEditNom, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(154, 154, 154)
                        .addComponent(jLabelModifCommune)))
                .addContainerGap(100, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabelModifCommune, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldEditNom, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldEditCodePostal, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldEditDescrip, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(100, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldEditDescripActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldEditDescripActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldEditDescripActionPerformed

    private void jTextFieldEditCodePostalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldEditCodePostalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldEditCodePostalActionPerformed

    private void jTextFieldEditNomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldEditNomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldEditNomActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelModifCommune;
    private javax.swing.JTextField jTextFieldEditCodePostal;
    private javax.swing.JTextField jTextFieldEditDescrip;
    private javax.swing.JTextField jTextFieldEditNom;
    // End of variables declaration//GEN-END:variables
    public String getNom() {
        return this.jTextFieldEditNom.getText();
    }

    public int getCodePostal() {
        return Integer.parseInt(this.jTextFieldEditCodePostal.getText());
    }

    public String getDescription() {
        return this.jTextFieldEditDescrip.getText();
    }

    public void setNom(String nom) {
        this.jTextFieldEditNom.setText(nom);
    }

    public void setCodePostal(int codePostal) {
        this.jTextFieldEditCodePostal.setText(String.valueOf(codePostal));
    }

    public void setDescription(String description) {
        this.jTextFieldEditDescrip.setText(description);
    }
    public void setJLabelModifCommune(String titre){
        this.jLabelModifCommune.setText(titre+" Commune");
    }
}
