/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.awt.CardLayout;
import model.Commune;

/**
 *
 * @author m.arakelian
 */
public class MainView extends javax.swing.JFrame {

    private UtilisateurView utilisateurView;
    private CommuneView communeView;

    /**
     * Creates new form MainView
     */
    public MainView() {
        initComponents();

        this.utilisateurView = new UtilisateurView();
        this.MainPanel.add(utilisateurView, "cardViewUtilisateur");

        this.communeView = new CommuneView();
        this.MainPanel.add(communeView, "cardViewCommune");

        CardLayout cardLayout = (CardLayout) this.MainPanel.getLayout();
        cardLayout.show(this.MainPanel, "cardViewCommune");
    }

    public CommuneView getCommuneView() {
        return this.communeView;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(716, 510));
        setMinimumSize(new java.awt.Dimension(716, 510));

        MainPanel.setPreferredSize(new java.awt.Dimension(716, 510));
        MainPanel.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 704, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel MainPanel;
    // End of variables declaration//GEN-END:variables
    public void useLayout(String cardtext) {
        CardLayout card = (CardLayout) MainPanel.getLayout();
        card.show(MainPanel, cardtext);
    }

    public UtilisateurView getUtilisateurView() {
        return this.utilisateurView;
    }
    
    public void showUserViewForCommune(Commune commune) {
        //this.utilisateurView.setCommune(commune);
        CardLayout card = (CardLayout) MainPanel.getLayout();
        card.show(MainPanel, "cardViewUtilisateur");

        card = (CardLayout) utilisateurView.getLayout();
        card.show(utilisateurView, "cardListeUtilisateur");
    }
    public void AffichageCommune(){
        CardLayout cardLayout = (CardLayout) this.MainPanel.getLayout();
        cardLayout.show(this.MainPanel, "cardViewCommune");
    }
}
