/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.awt.CardLayout;

/**
 *
 * @author m.arakelian
 */
public class MainView extends javax.swing.JFrame {

    private UtilisateurView utilisateurView;
    private CommuneView communeView;

    /**
     * Creates new form MainView
     */
    public MainView() {
        initComponents();

        this.utilisateurView = new UtilisateurView();
        this.MainPanel.add(utilisateurView, "cardViewUtilisateur");

        this.communeView = new CommuneView();
        this.MainPanel.add(communeView, "cardViewCommune");

        CardLayout cardLayout = (CardLayout) this.MainPanel.getLayout();
        cardLayout.show(this.MainPanel, "cardViewCommune");
    }

    public CommuneView getCommuneView() {
        return this.communeView;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainPanel = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        CheckBoxUtilisateurListe = new javax.swing.JCheckBoxMenuItem();
        CheckBoxUtilisateurAjout = new javax.swing.JCheckBoxMenuItem();
        CheckBoxUtilisateurModif = new javax.swing.JCheckBoxMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(716, 510));
        setMinimumSize(new java.awt.Dimension(716, 510));

        MainPanel.setPreferredSize(new java.awt.Dimension(716, 510));
        MainPanel.setLayout(new java.awt.CardLayout());

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");

        CheckBoxUtilisateurListe.setSelected(true);
        CheckBoxUtilisateurListe.setText("CheckBoxUtilisateur");
        CheckBoxUtilisateurListe.setActionCommand("");
        CheckBoxUtilisateurListe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckBoxUtilisateurListeActionPerformed(evt);
            }
        });
        jMenu2.add(CheckBoxUtilisateurListe);

        CheckBoxUtilisateurAjout.setSelected(true);
        CheckBoxUtilisateurAjout.setText("jCheckBoxMenuItem2");
        CheckBoxUtilisateurAjout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckBoxUtilisateurAjoutActionPerformed(evt);
            }
        });
        jMenu2.add(CheckBoxUtilisateurAjout);

        CheckBoxUtilisateurModif.setSelected(true);
        CheckBoxUtilisateurModif.setText("jCheckBoxMenuItem1");
        CheckBoxUtilisateurModif.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckBoxUtilisateurModifActionPerformed(evt);
            }
        });
        jMenu2.add(CheckBoxUtilisateurModif);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 704, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 487, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CheckBoxUtilisateurAjoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckBoxUtilisateurAjoutActionPerformed
        // TODO add your handling code here:
        CardLayout card = (CardLayout) MainPanel.getLayout();
        card.show(MainPanel, "cardViewUtilisateur");

        card = (CardLayout) utilisateurView.getLayout();
        card.show(utilisateurView, "cardEditUtilisateur");

    }//GEN-LAST:event_CheckBoxUtilisateurAjoutActionPerformed

    private void CheckBoxUtilisateurListeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckBoxUtilisateurListeActionPerformed
        // TODO add your handling code here:
        CardLayout card = (CardLayout) MainPanel.getLayout();
        card.show(MainPanel, "cardViewUtilisateur");

        card = (CardLayout) utilisateurView.getLayout();
        card.show(utilisateurView, "cardListeUtilisateur");

    }//GEN-LAST:event_CheckBoxUtilisateurListeActionPerformed

    private void CheckBoxUtilisateurModifActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckBoxUtilisateurModifActionPerformed
        CardLayout card = (CardLayout) MainPanel.getLayout();
        card.show(MainPanel, "cardViewUtilisateur");

        card = (CardLayout) utilisateurView.getLayout();
        card.show(utilisateurView, "cardEditUtilisateur");

    }//GEN-LAST:event_CheckBoxUtilisateurModifActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBoxMenuItem CheckBoxUtilisateurAjout;
    private javax.swing.JCheckBoxMenuItem CheckBoxUtilisateurListe;
    private javax.swing.JCheckBoxMenuItem CheckBoxUtilisateurModif;
    private javax.swing.JPanel MainPanel;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
    public void useLayout(String cardtext) {
        CardLayout card = (CardLayout) MainPanel.getLayout();
        card.show(MainPanel, cardtext);
    }

    public UtilisateurView getUtilisateurView() {
        return this.utilisateurView;
    }
}
