/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import javax.swing.JTextField;

/**
 *
 * @author m.arakelian
 */
public class UtilisateurEditPanel extends javax.swing.JPanel {

    /**
     * Creates new form EditUtilisateurPanel
     */
    public UtilisateurEditPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelTitreEditUtilisateur = new javax.swing.JLabel();
        jLabelEditPrenomUtilisateur = new javax.swing.JLabel();
        jTextFieldEditPrenomUtilisateur = new javax.swing.JTextField();
        jLabelEditNomUtilisateur = new javax.swing.JLabel();
        jTextFieldEditNomUtilisateur = new javax.swing.JTextField();
        jLabelEditIdentifiantUtilisateur = new javax.swing.JLabel();
        jTextFieldEditIdentifiantUtilisateur = new javax.swing.JTextField();
        jLabelEditPasswordUtilisateur = new javax.swing.JLabel();
        jTextFieldPasswordEditUtilisateur = new javax.swing.JTextField();

        jLabelTitreEditUtilisateur.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        jLabelTitreEditUtilisateur.setText("Ajout Utilisateur");

        jLabelEditPrenomUtilisateur.setText("Prenom");

        jTextFieldEditPrenomUtilisateur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldEditPrenomUtilisateurActionPerformed(evt);
            }
        });

        jLabelEditNomUtilisateur.setText("Nom");

        jTextFieldEditNomUtilisateur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldEditNomUtilisateurActionPerformed(evt);
            }
        });

        jLabelEditIdentifiantUtilisateur.setText("Identifiant");

        jTextFieldEditIdentifiantUtilisateur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldEditIdentifiantUtilisateurActionPerformed(evt);
            }
        });

        jLabelEditPasswordUtilisateur.setText("Mot de Passe");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(250, 250, 250)
                .addComponent(jLabelTitreEditUtilisateur)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(78, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelEditPrenomUtilisateur)
                    .addComponent(jTextFieldEditIdentifiantUtilisateur, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldEditPrenomUtilisateur, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldEditNomUtilisateur, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldPasswordEditUtilisateur, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelEditPasswordUtilisateur)
                    .addComponent(jLabelEditIdentifiantUtilisateur)
                    .addComponent(jLabelEditNomUtilisateur))
                .addGap(77, 77, 77))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jLabelTitreEditUtilisateur)
                .addGap(31, 31, 31)
                .addComponent(jLabelEditPrenomUtilisateur)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldEditPrenomUtilisateur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(jLabelEditNomUtilisateur)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldEditNomUtilisateur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(jLabelEditIdentifiantUtilisateur)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldEditIdentifiantUtilisateur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(jLabelEditPasswordUtilisateur)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldPasswordEditUtilisateur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(81, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldEditPrenomUtilisateurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldEditPrenomUtilisateurActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldEditPrenomUtilisateurActionPerformed

    private void jTextFieldEditNomUtilisateurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldEditNomUtilisateurActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldEditNomUtilisateurActionPerformed

    private void jTextFieldEditIdentifiantUtilisateurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldEditIdentifiantUtilisateurActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldEditIdentifiantUtilisateurActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelEditIdentifiantUtilisateur;
    private javax.swing.JLabel jLabelEditNomUtilisateur;
    private javax.swing.JLabel jLabelEditPasswordUtilisateur;
    private javax.swing.JLabel jLabelEditPrenomUtilisateur;
    private javax.swing.JLabel jLabelTitreEditUtilisateur;
    private javax.swing.JTextField jTextFieldEditIdentifiantUtilisateur;
    private javax.swing.JTextField jTextFieldEditNomUtilisateur;
    private javax.swing.JTextField jTextFieldEditPrenomUtilisateur;
    private javax.swing.JTextField jTextFieldPasswordEditUtilisateur;
    // End of variables declaration//GEN-END:variables

    public void setEditPanel(String prenom, String nom, String login, String password) {
        this.jTextFieldEditNomUtilisateur.setText(nom);
        this.jTextFieldEditPrenomUtilisateur.setText(prenom);
        this.jTextFieldEditIdentifiantUtilisateur.setText(login);
        this.jTextFieldPasswordEditUtilisateur.setText(password);
    }

    public String getLoginUtilisateur() {
        return this.jTextFieldEditIdentifiantUtilisateur.getText();
    }

    public String getNomUtilisateur() {
        return this.jTextFieldEditNomUtilisateur.getText();
    }

    public String getPrenomUtilisateur() {
        return this.jTextFieldEditPrenomUtilisateur.getText();
    }

    public String getPasswordUtilisateur() {
        return this.jTextFieldPasswordEditUtilisateur.getText();
    }
    
   
}
