/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import java.awt.CardLayout;
import java.beans.PropertyChangeSupport;
import java.beans.PropertyChangeListener;
import javax.swing.JOptionPane;
import model.UtilisateurListModel;

/**
 *
 * @author j.bonnafe
 */
public class UtilisateurView extends javax.swing.JPanel {

    private PropertyChangeSupport listeners = new PropertyChangeSupport(this);
    private UtilisateurEditPanel utilisateurEditPanel= new UtilisateurEditPanel();
    
    public UtilisateurView() {
        initComponents(); 
    }
    
    @Override
    public void addPropertyChangeListener(PropertyChangeListener l) {
        listeners.addPropertyChangeListener(l);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPaneUtilisateur = new javax.swing.JScrollPane();
        jListUtilisateur = new javax.swing.JList<>();
        jLabelTitreListeUtilisateur = new javax.swing.JLabel();
        jButtonAjouterListeUtilisateur = new javax.swing.JButton();
        jButtonModifierListeUtilisateur = new javax.swing.JButton();
        jButtonSupprimerListeUtilisateur = new javax.swing.JButton();

        jListUtilisateur.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPaneUtilisateur.setViewportView(jListUtilisateur);

        jLabelTitreListeUtilisateur.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabelTitreListeUtilisateur.setText("Liste des utilisateurs de ");

        jButtonAjouterListeUtilisateur.setText("Ajouter");
        jButtonAjouterListeUtilisateur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAjouterListeUtilisateurActionPerformed(evt);
            }
        });

        jButtonModifierListeUtilisateur.setText("Modification");
        jButtonModifierListeUtilisateur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModifierListeUtilisateurActionPerformed(evt);
            }
        });

        jButtonSupprimerListeUtilisateur.setText("Supprimer");
        jButtonSupprimerListeUtilisateur.setToolTipText("");
        jButtonSupprimerListeUtilisateur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSupprimerListeUtilisateurActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(148, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButtonModifierListeUtilisateur)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButtonSupprimerListeUtilisateur))
                            .addComponent(jScrollPaneUtilisateur, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(143, 143, 143))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(122, 122, 122)
                        .addComponent(jLabelTitreListeUtilisateur, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonAjouterListeUtilisateur)))
                .addGap(112, 112, 112))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAjouterListeUtilisateur)
                    .addComponent(jLabelTitreListeUtilisateur, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addComponent(jScrollPaneUtilisateur, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(80, 80, 80)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonModifierListeUtilisateur)
                    .addComponent(jButtonSupprimerListeUtilisateur))
                .addContainerGap(78, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonModifierListeUtilisateurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModifierListeUtilisateurActionPerformed
        listeners.firePropertyChange("AffichageModificationUtilisateur", null, null);
        String[] options = {"Valider", "Annuler"};
        int result = JOptionPane.showOptionDialog(
                this,
                this.utilisateurEditPanel,
                "Ajout nouvelle utilisateur",
                JOptionPane.OK_CANCEL_OPTION,
                JOptionPane.PLAIN_MESSAGE,
                null,
                options,
                options[0]
        );
        if (result == JOptionPane.OK_OPTION) {
            listeners.firePropertyChange("ConfirmModificationUtilisateur", null, null);
        }
    }//GEN-LAST:event_jButtonModifierListeUtilisateurActionPerformed

    private void jButtonAjouterListeUtilisateurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAjouterListeUtilisateurActionPerformed
        String[] options = {"Valider", "Annuler"};
        int result = JOptionPane.showOptionDialog(
                this,
                this.utilisateurEditPanel,
                "Ajout nouvelle utilisateur",
                JOptionPane.OK_CANCEL_OPTION,
                JOptionPane.PLAIN_MESSAGE,
                null,
                options,
                options[0]
        );
        if (result == JOptionPane.OK_OPTION) {
            listeners.firePropertyChange("AjoutUtilisateur", null, null);
        }
    }//GEN-LAST:event_jButtonAjouterListeUtilisateurActionPerformed

    private void jButtonSupprimerListeUtilisateurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSupprimerListeUtilisateurActionPerformed
    int result = JOptionPane.showConfirmDialog(this, "Etes vous certain de supprimer cette utilisateur ?");
        if (result == JOptionPane.OK_OPTION) {
            if(this.getUtilisateurIndex()!=-1){
                listeners.firePropertyChange("suppressionUtilisateur", null, null);
            } else {
                JOptionPane.showMessageDialog(this, "Veuillez sélectionner un utilisateur pour pouvoir le supprimer.");
            }
        }
    }//GEN-LAST:event_jButtonSupprimerListeUtilisateurActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAjouterListeUtilisateur;
    private javax.swing.JButton jButtonModifierListeUtilisateur;
    private javax.swing.JButton jButtonSupprimerListeUtilisateur;
    private javax.swing.JLabel jLabelTitreListeUtilisateur;
    private javax.swing.JList<String> jListUtilisateur;
    private javax.swing.JScrollPane jScrollPaneUtilisateur;
    // End of variables declaration//GEN-END:variables

    public void setUtilisateurListModel(UtilisateurListModel utilisateurListModel) {
        System.out.println(utilisateurListModel);
        this.jListUtilisateur.setModel(utilisateurListModel);
    }
    public int getUtilisateurIndex(){
        System.out.println(this.jListUtilisateur.getSelectedIndex());
        return this.jListUtilisateur.getSelectedIndex();    
    }
    public void accesSetEditPanel(String prenom,String nom, String login,String password){
        this.utilisateurEditPanel.setEditPanel(prenom,nom,login,password);
    
    }
    public String accessGetNomUtilisateur (){
        return(this.utilisateurEditPanel.getNomUtilisateur());
    }
    public String accessGetPrenomUtilisateur (){
        return this.utilisateurEditPanel.getPrenomUtilisateur();
    }
    public String accessGetLoginUtilisateur (){
        return this.utilisateurEditPanel.getLoginUtilisateur();
    }
    public String accessGetPasswordUtilisateur (){
        return this.utilisateurEditPanel.getPasswordUtilisateur();
    }
}
